[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=29C22A254A081C14272BB68C0D403B2F
ProjectName=Third Person Game Template

[/Script/UnrealEd.ProjectPackagingSettings]
+MapsToCook=(FilePath="/Game/Maps/L_MainMenu")
+MapsToCook=(FilePath="/Game/Maps/L_Lobby")
; +MapsToCook=(FilePath="/Game/BattleRoyaleStarterKit/Maps/BattleRoyale_Map_a/BattleRoyale_Map_a_WP")
+MapsToCook=(FilePath="/Game/Maps/Map_BattleRoyale")

[/Script/BattlegroundClone.SessionApiSubsystem]
BaseUrl="http://localhost:8080"

[ConsoleVariables]
CommonUI.CheckKeyboardFocusAndParentage=1
CommonUI.DisallowUserFocusedWidgetForPendingFocusRecipient=1
CommonUI.FallbackToDesiredOnAutoRestoreFailure=1
